analytics: {}
color:
  brandColors:
    - '#D0C0A0'
    - '#5B482A'
    - '#807070'
    - '#C8B088'
    - '#E0D0B0'
  brandStrength: 1
  lightness: 0.991554
  rhythmicContrast: 1
  saturation: 0.780405
cta: {}
layout_spectrum: 0.763513
name: 'Hamilton '
opengraph: {}
purpose: []
typography_spectrum: 0.618243
