name: 'Hamilton '
favicon: null
layout_spectrum: 0.93208
typography_spectrum: 0.35816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030406'
    - '#162c41'
    - '#406086'
    - '#9eb7d5'
    - '#ccdcf6'
  brandStrength: 1
  lightness: 0.991554
  saturation: 0.780405
  rhythmicContrast: 1
purpose: []
