name: 'Hamilton '
favicon: null
layout_spectrum: 0.12342
typography_spectrum: 0.30987
title: Observando o passado para construir o futuro.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#ff7d00'
    - '#acacac'
    - '#000203'
  brandStrength: 0.0625
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.5
purpose: []
